### ISSUE TITLE
[FEAT/REFACTOR/BUG/DOCS] 절대 이슈 발행이 귀찮아서 하나로 합친게 아닙니다.

### ISSUE THREAD

**Issue by kooqooo** [boostcampaitech6/level2-klue-nlp-04#15]
## Background
- 쉘 코드로 파일을 돌리려다가 여러가지 문제점들을 발견하여 다시 대규모 수정이 있었습니다.

## To do 
- [x] black 자동 포맷팅 툴 때문에 `train.py`의 주석이 안예쁘게 나오는거 보기 좋게 수정
- [x] `config.yaml` 파일이 많아질 것을 대비하여 config 폴더 생성
- [x] 쉘 코드를 통하여 여러 config 파일 모두 실행되도록 쉘코드 생성과 Makefile 변경
- [x] 그에 맞게 `default_config.yaml` 파일 수정
- [x] 여러 파일을 돌리면 output이 여러개가 나오는데, 파일 이름 다양하게 저장되도록 `inference.py` 수정
- [x] 어떻게 사용할 수 있는지 README.md 수정
- [x] 기타 소소한 마이너 변경사항들...

**Comment by ohbigkite** [comment]
많은 것을 해주셨네요. 감사합니다. 😭
