### ISSUE TITLE
[FEAT]  random seeds 적용하기!

### ISSUE THREAD

**Issue by yeh-jeans** [boostcampaitech6/level2-klue-nlp-04#20]
## Background
-  같은 모델이라도 랜덤시드를 정해주지 않으면 재현성공율이 떨어질 수 있습니다. 재현시 환경 설정을 위해 랜덤 시드값을 고정하여 적용합시다

## To do 
- [x] config.yaml 에 seeds 변수를 추가합니다
- [x] train 에 set_seed() 함수를 추가 후 train 실행 시 실행합니다.

일단 저번 대회 때와 같은 코드로 적용하였습니다. 적용이 잘 되는건지는 한번 더 확인 할 필요가 있다...

**Comment by maxseats** [comment]
좋은 코드 감사합니다.

set_seed함수를 기존대로
set_seed(seed=42)로 두고,
train함수 첫 부분에서 seeds=cfg["params]["seeds"]로 설정해서 
set_seed(seeds)으로 적용하면 더 좋을 것 같습니다!

**Comment by yeh-jeans** [comment]
의견 왕감사합니다. 
말씀하신대로 수정하였습니다
