### ISSUE TITLE
[BUG] feat/24에서 merge된 develop/maxseats와 develop/yejeans 충돌 해결하기

### ISSUE THREAD

**Issue by kooqooo** [boostcampaitech6/level2-klue-nlp-04#29]
## Describe the bug
- feat/24에서 merge된 develop/maxseats와 develop/yejeans 충돌 해결하기
- 그래서 feat/24에 있는 내용은 현재 develop/maxseats 브랜치에 있지만, 편의상 feat/24라고 하겠습니다.

## 해결과정
1. Merge: feat/24 -> develop/maxseats
2. checkout devlop/yehjeans
3. [feat/24]`.gitignore`: feat/24 채택
4. [feat/24]`README.md`: feat/24 채택
5. [feat/24]`inference.py`의 config 경로: feat/24 채택
6. [feat/24]`inference.py`의 prediction 파일 이름에 micro_f1, auprc 적용하기
7. [develop/yejeans]`load_data.py`의 75번 줄 return_token_type_ids 제거
8. [feat/24] `utils/preprocessing.py` 추가
9. `train.py`는 의논이 필요해서 아래에 기재

## `train.py`에서 의논 or 해결할 내용
- [x] WandB 작동 방식 (wandb.init(), training_args의 매개변수) 
- [x] 주석처리된 early_stopping
- [x] confing 파일의 경로
- [x] bigohkite -> maxseats
- [x] yehjeans -> maxseats

**Comment by yeh-jeans** [comment]
봐주셔서 감사합니다. 주석처리된 early 스탑핑 코드는 수정하였습니다. 리펙토링이 필요할경우 편하게 알려주시거나 해주셔도 됩니다!

**Comment by kooqooo** [comment]
나머지는 충돌해결 했는데 train.py는 같이 의논이 필요해서 아침에 의논해봐요. 수고했어요

**Comment by kooqooo** [comment]
?? Assignees 여러명 할당 못하나요??

**Comment by ohbigkite** [comment]
어떻게 된건진 모르겠지만... 제 것도 합쳐주세오.......
일단 저는 현 시점 maxseats에서 branch파서 작업중입니다..!

**Comment by kooqooo** [comment]
@ohbigkite 그러면 maxseats로 병합할게요! 그리고 아침에 의논해보겠습니당.

**Comment by ohbigkite** [comment]
@kooqooo difference.csv 만드는 거에 파일 이름 설정 기능 추가#31 해서 feat/31 브랜치를 또 팠어요!ㅎㅎ 
이거를 최종적으로 병합해주시면 감사하겠습니다 ㅎㅎ!!
