### ISSUE TITLE
[FEAT] difference.csv 파일 최종 한번만 출력되도록 수정

### ISSUE THREAD

**Issue by ohbigkite** [boostcampaitech6/level2-klue-nlp-04#34]
## Background
- compute_metrics에 save_preds_to_csv함수를 넣었더니 한 epoch마다 difference.csv가 나오는 것을 확인.
- 최종 결과만을 확인하면 되므로 최종 model이 예측하는 valid difference 값만 출력하도록 수정 

## To do 
- [x] 최종적으로 선정되는 모델의 valid 평가값만을 출력하도록 수정
- [x] 파일 저장 이름 변경 - acc 대신 auprc, mico f1 출력되도록!
- [x] 오답과 정답 구분하는 열 만들기

**Comment by kooqooo** [comment]
이거 해보겠다고 시간 쏟다가 실패했어요,,,, ㅋㅋ ㅠㅠ
차라리 마지막에 필요 없는 파일을 삭제하는 방향으로 해보는 게 낫겠어요

**Comment by kooqooo** [comment]
결국 해내셨군요 수고하셨어요
